language: go
before_install:
  - go get github.com/stretchr/testify/assert


script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go test ./... -short

after_success:
  - bash <(curl -s https://codecov.io/bash)
